# wrangler.toml (used by Pages on deploy)
name = "thehoffmans-wedding"
compatibility_date = "2025-09-15"
pages_build_output_dir = "dist"

# --- Production binding for Pages ---
[[d1_databases]]
binding = "DB"
database_name = "wedding_rsvp"
database_id = "b5254ca7-205c-46e1-b96f-1275987fb241"

# --- Preview binding for Pages ---
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "wedding_rsvp"
database_id = "b5254ca7-205c-46e1-b96f-1275987fb241"

# (Optional) local dev prefs (no D1 binding here—see step 3)
[dev]
port = 8787